name: smart_lib_dialog
description: A Flutter library that provides custom dialogs with back button interception.
version: 1.0.3

homepage: https://github.com/vanik98/smart_lib_dialog
repository: https://github.com/vanik98/smart_lib_dialog
issue_tracker: https://github.com/vanik98/smart_lib_dialog/issues

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  back_button_interceptor: ^8.0.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true